%足先リンク（metatarsal）の重心速度　calc_EOM_workから書き出されたファイル

function dx_met_CoM_vec = calc_dx_met_CoM_vec(in1,in2,in3,in4)
%calc_dx_met_CoM_vec
%    dx_met_CoM_vec = calc_dx_met_CoM_vec(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Jul-2024 23:01:49

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M_met_beam = in1(9,:);
M_met_pulley = in1(8,:);
dtheta1 = in4(5,:);
dtheta2 = in4(6,:);
dtheta3 = in4(7,:);
dtheta4 = in4(8,:);
dx1 = in4(1,:);
dy1 = in4(2,:);
theta1 = in3(5,:);
theta2 = in3(6,:);
theta3 = in3(7,:);
theta4 = in3(8,:);
t2 = theta1+theta2;
t3 = M_met_beam+M_met_pulley;
t4 = cos(t2);
t5 = sin(t2);
t6 = t2+theta3;
t11 = 1.0./t3;
t7 = cos(t6);
t8 = sin(t6);
t9 = t6+theta4;
t10 = L_fem.*t4;
t12 = L_fem.*t5;
t13 = cos(t9);
t14 = sin(t9);
t15 = L_tib.*t7;
t16 = L_tib.*t8;
t17 = (L_met.*M_met_beam.*t11.*t13)./2.0;
t18 = (L_met.*M_met_beam.*t11.*t14)./2.0;
dx_met_CoM_vec = [dx1+dtheta1.*(t10+t15+t17+L_frame.*cos(theta1))+dtheta3.*(t15+t17)+dtheta4.*t17+dtheta2.*(t10+t15+t17);dy1+dtheta3.*(t16+t18)+dtheta1.*(t12+t16+t18+L_frame.*sin(theta1))+dtheta4.*t18+dtheta2.*(t12+t16+t18)];
