function dx_tib_CoM_vec = calc_dx_tib_CoM_vec(in1,in2,in3)
%calc_dx_tib_CoM_vec
%    dx_tib_CoM_vec = calc_dx_tib_CoM_vec(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Jul-2024 23:01:49

L_fem = in1(1,:);
L_frame = in1(6,:);
L_tib = in1(2,:);
dtheta1 = in3(5,:);
dtheta2 = in3(6,:);
dtheta3 = in3(7,:);
dx1 = in3(1,:);
dy1 = in3(2,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
theta3 = in2(7,:);
t2 = theta1+theta2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+theta3;
t6 = cos(t5);
t7 = sin(t5);
t8 = L_fem.*t3;
t9 = L_fem.*t4;
t10 = (L_tib.*t6)./2.0;
t11 = (L_tib.*t7)./2.0;
dx_tib_CoM_vec = [dx1+dtheta2.*(t8+t10)+dtheta3.*t10+dtheta1.*(t8+t10+L_frame.*cos(theta1));dy1+dtheta2.*(t9+t11)+dtheta3.*t11+dtheta1.*(t9+t11+L_frame.*sin(theta1))];
