%踵のy座標　calc_EOM_workから書き出されたファイル

function y_heel = calc_y_heel(in1,in2)
%CALC_Y_HEEL
%    Y_HEEL = CALC_Y_HEEL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:16

L_fem = in1(1,:);
L_frame = in1(6,:);
L_tib = in1(2,:);
r = in1(7,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
theta3 = in2(7,:);
y1 = in2(2,:);
t2 = theta1+theta2;
y_heel = -r+y1-L_tib.*cos(t2+theta3)-L_fem.*cos(t2)-L_frame.*cos(theta1);
