%重心の運動量の計算　calc_EOM_workから書き出されたファイル

function momentum_COM_list = calc_momentum_COM_list(in1,in2,in3,in4)
%calc_momentum_COM_list
%    momentum_COM_list = calc_momentum_COM_list(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/22 09:09:59

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M_fem = in1(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
M_met = in1(10,:);
M_met_rod = in1(9,:);
M_met_pulley = in1(8,:);
M_tib = in1(7,:);
dtheta1 = in4(5,:);
dtheta2 = in4(6,:);
dtheta3 = in4(7,:);
dtheta4 = in4(8,:);
dx1 = in4(1,:);
dy1 = in4(2,:);
theta1 = in3(5,:);
theta2 = in3(6,:);
theta3 = in3(7,:);
theta4 = in3(8,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = theta1+theta2;
t5 = L_frame.*M_hip;
t6 = M_frame+M_hip;
t7 = M_met+M_met_pulley;
t8 = M_met_rod+M_met_pulley;
t23 = (L_frame.*M_frame)./2.0;
t9 = L_frame.*t2;
t10 = L_frame.*t3;
t11 = cos(t4);
t12 = sin(t4);
t13 = t4+theta3;
t18 = 1.0./t6;
t19 = 1.0./t8;
t26 = t5+t23;
t14 = cos(t13);
t15 = sin(t13);
t16 = t13+theta4;
t17 = L_fem.*t11;
t20 = L_fem.*t12;
t21 = cos(t16);
t22 = sin(t16);
t24 = L_tib.*t14;
t25 = L_tib.*t15;
t27 = t24./2.0;
t28 = t25./2.0;
t29 = (L_met.*M_met_rod.*t19.*t21)./2.0;
t30 = (L_met.*M_met_rod.*t19.*t22)./2.0;
momentum_COM_list = [t6.*(dx1+dtheta1.*t2.*t18.*t26);t6.*(dy1+dtheta1.*t3.*t18.*t26);M_fem.*(dx1+(dtheta2.*t17)./2.0+dtheta1.*(t9+t17./2.0));M_fem.*(dy1+(dtheta2.*t20)./2.0+dtheta1.*(t10+t20./2.0));M_tib.*(dx1+dtheta2.*(t17+t27)+dtheta3.*t27+dtheta1.*(t9+t17+t27));M_tib.*(dy1+dtheta2.*(t20+t28)+dtheta3.*t28+dtheta1.*(t10+t20+t28));t7.*(dx1+dtheta3.*(t24+t29)+dtheta4.*t29+dtheta2.*(t17+t24+t29)+dtheta1.*(t9+t17+t24+t29));t7.*(dy1+dtheta3.*(t25+t30)+dtheta4.*t30+dtheta2.*(t20+t25+t30)+dtheta1.*(t10+t20+t25+t30))];
end
