function COM_link = calc_COM_link(in1,in2,in3)
%calc_COM_link
%    COM_link = calc_COM_link(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/11/12 15:39:36

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M_fem = in1(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
M_met = in1(10,:);
M_met_rod = in1(9,:);
M_met_pulley = in1(8,:);
M_tib = in1(7,:);
theta1 = in3(5,:);
theta2 = in3(6,:);
theta3 = in3(7,:);
theta4 = in3(8,:);
x1 = in3(1,:);
y1 = in3(2,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = theta1+theta2;
t5 = L_frame.*M_hip;
t6 = M_frame+M_hip;
t7 = M_met_rod+M_met_pulley;
t13 = -y1;
t17 = M_fem+M_frame+M_met+M_tib;
t22 = (L_frame.*M_frame)./2.0;
t8 = L_frame.*t2;
t9 = L_frame.*t3;
t10 = cos(t4);
t11 = sin(t4);
t12 = t4+theta3;
t19 = 1.0./t6;
t20 = 1.0./t7;
t23 = 1.0./t17;
t24 = t5+t22;
t14 = cos(t12);
t15 = sin(t12);
t16 = t12+theta4;
t18 = L_fem.*t10;
t21 = L_fem.*t11;
COM_link = [t23.*(M_frame.*(x1+t3.*t19.*t24)+M_tib.*(t9+t21+x1+(L_tib.*t15)./2.0)+M_fem.*(t9+t21./2.0+x1)+M_met.*(t9+t21+x1+L_tib.*t15+(L_met.*M_met_rod.*t20.*sin(t16))./2.0));-t23.*(-M_frame.*(y1-t2.*t19.*t24)+M_tib.*(t8+t13+t18+(L_tib.*t14)./2.0)+M_fem.*(t8+t13+t18./2.0)+M_met.*(t8+t13+t18+L_tib.*t14+(L_met.*M_met_rod.*t20.*cos(t16))./2.0))];
end
