%つま先のy座標　calc_EOM_workから書き出されたファイル

function y_toe = calc_y_toe(in1,in2)
%CALC_Y_TOE
%    Y_TOE = CALC_Y_TOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:16

L_fem = in1(1,:);
L_frame = in1(6,:);
L_met = in1(3,:);
L_tib = in1(2,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
theta3 = in2(7,:);
theta4 = in2(8,:);
y1 = in2(2,:);
t2 = theta1+theta2;
t3 = t2+theta3;
y_toe = y1-L_met.*cos(t3+theta4)-L_fem.*cos(t2)-L_tib.*cos(t3)-L_frame.*cos(theta1);
