function T_gravity_all = calc_torque_gravity_all(in1,in2,in3,in4,g)
%CALC_TORQUE_GRAVITY_ALL
%    T_gravity_all = CALC_TORQUE_GRAVITY_ALL(IN1,IN2,IN3,IN4,G)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/28 13:09:10

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M2 = in1(2,:);
M3 = in1(3,:);
M_fem = in1(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
M_met = in1(10,:);
M_met_rod = in1(9,:);
M_met_pulley = in1(8,:);
M_tib = in1(7,:);
l_CFL = in4(10,:);
theta1 = in4(5,:);
theta2 = in4(6,:);
theta3 = in4(7,:);
theta4 = in4(8,:);
theta_CFL = in4(9,:);
t2 = sin(theta1);
t3 = theta1+theta2;
t4 = M_met_rod+M_met_pulley;
t5 = L_frame.*t2;
t6 = sin(t3);
t7 = t3+theta3;
t10 = 1.0./t4;
t8 = sin(t7);
t9 = t7+theta4;
t11 = L_fem.*t6;
t12 = sin(t9);
t13 = L_tib.*t8;
t14 = t13./2.0;
t15 = (L_met.*M_met_rod.*t10.*t12)./2.0;
T_gravity_all = [0.0;-M2.*g;0.0;0.0;0.0;0.0;0.0;0.0;-M2.*g.*l_CFL.*sin(theta_CFL);M2.*g.*cos(theta_CFL);0.0;0.0;0.0;-M3.*g;0.0;0.0;0.0;0.0;0.0;0.0;0.0;-g.*(M_frame+M_hip);0.0;0.0;-g.*t2.*((L_frame.*M_frame)./2.0+L_frame.*M_hip);0.0;0.0;0.0;0.0;0.0;0.0;-M_fem.*g;0.0;0.0;-M_fem.*g.*(t5+t11./2.0);M_fem.*g.*t11.*(-1.0./2.0);0.0;0.0;0.0;0.0;0.0;-M_tib.*g;0.0;0.0;-M_tib.*g.*(t5+t11+t14);-M_tib.*g.*(t11+t14);M_tib.*g.*t13.*(-1.0./2.0);0.0;0.0;0.0;0.0;-M_met.*g;0.0;0.0;-M_met.*g.*(t5+t11+t13+t15);-M_met.*g.*(t11+t13+t15);-M_met.*g.*(t13+t15);L_met.*M_met.*M_met_rod.*g.*t10.*t12.*(-1.0./2.0);0.0;0.0];
end
