%股関節の速度ベクトル　calc_EOM_workから書き出されたファイル

function dx_hip_vec = calc_dx_hip_vec(in1,in2,in3)
%CALC_DX_HIP_VEC
%    DX_HIP_VEC = CALC_DX_HIP_VEC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:14

L_frame = in1(6,:);
dtheta1 = in3(5,:);
dx1 = in3(1,:);
dy1 = in3(2,:);
theta1 = in2(5,:);
dx_hip_vec = [dx1+L_frame.*dtheta1.*cos(theta1);dy1+L_frame.*dtheta1.*sin(theta1)];
