function dx_toe_vec = calc_dx_toe_vec(in1,in2,in3)
%CALC_DX_TOE_VEC
%    DX_TOE_VEC = CALC_DX_TOE_VEC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:14

L_fem = in1(1,:);
L_frame = in1(6,:);
L_met = in1(3,:);
L_tib = in1(2,:);
dtheta1 = in3(5,:);
dtheta2 = in3(6,:);
dtheta3 = in3(7,:);
dtheta4 = in3(8,:);
dx1 = in3(1,:);
dy1 = in3(2,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
theta3 = in2(7,:);
theta4 = in2(8,:);
t2 = theta1+theta2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+theta3;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+theta4;
t9 = L_fem.*t3;
t10 = L_fem.*t4;
t11 = cos(t8);
t12 = sin(t8);
t13 = L_tib.*t6;
t14 = L_tib.*t7;
t15 = L_met.*t11;
t16 = L_met.*t12;
dx_toe_vec = [dx1+dtheta1.*(t9+t13+t15+L_frame.*cos(theta1))+dtheta3.*(t13+t15)+dtheta4.*t15+dtheta2.*(t9+t13+t15);dy1+dtheta3.*(t14+t16)+dtheta1.*(t10+t14+t16+L_frame.*sin(theta1))+dtheta4.*t16+dtheta2.*(t10+t14+t16)];
