%全体の重心位置の座標　calc_EOM_workから書き出されたファイル

function COM = calc_COM(in1,in2,in3)
%calc_COM
%    COM = calc_COM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:23

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M1 = in1(1,:);
M2 = in1(2,:);
M3 = in1(3,:);
M_fem = in1(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
M_met = in1(10,:);
M_met_beam = in1(9,:);
M_met_pulley = in1(8,:);
M_tib = in1(7,:);
l_CFL = in3(10,:);
theta1 = in3(5,:);
theta2 = in3(6,:);
theta3 = in3(7,:);
theta4 = in3(8,:);
theta_CFL = in3(9,:);
x1 = in3(1,:);
x3 = in3(3,:);
y1 = in3(2,:);
y3 = in3(4,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = theta1+theta2;
t5 = L_frame.*M_hip;
t6 = M_frame+M_hip;
t7 = M_met_beam+M_met_pulley;
t13 = -y1;
t21 = (L_frame.*M_frame)./2.0;
t22 = M1+M2+M3+M_fem+M_frame+M_met+M_tib;
t8 = L_frame.*t2;
t9 = L_frame.*t3;
t10 = cos(t4);
t11 = sin(t4);
t12 = t4+theta3;
t18 = 1.0./t6;
t19 = 1.0./t7;
t23 = t5+t21;
t24 = 1.0./t22;
t14 = cos(t12);
t15 = sin(t12);
t16 = t12+theta4;
t17 = L_fem.*t10;
t20 = L_fem.*t11;
COM = [t24.*(M1.*x1+M3.*x3+M2.*(x1+l_CFL.*sin(theta_CFL))+M_frame.*(x1+t3.*t18.*t23)+M_tib.*(t9+t20+x1+(L_tib.*t15)./2.0)+M_fem.*(t9+t20./2.0+x1)+M_met.*(t9+t20+x1+L_tib.*t15+(L_met.*M_met_beam.*t19.*sin(t16))./2.0));t24.*(M1.*y1+M3.*y3+M2.*(y1-l_CFL.*cos(theta_CFL))+M_frame.*(y1-t2.*t18.*t23)-M_tib.*(t8+t13+t17+(L_tib.*t14)./2.0)-M_fem.*(t8+t13+t17./2.0)-M_met.*(t8+t13+t17+L_tib.*t14+(L_met.*M_met_beam.*t19.*cos(t16))./2.0))];
