function dx_frame_CoM_vec = calc_dx_frame_CoM_vec(in1,in2,in3,in4)
%calc_dx_frame_CoM_vec
%    dx_frame_CoM_vec = calc_dx_frame_CoM_vec(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/31 01:51:19

L_frame = in2(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
dtheta1 = in4(5,:);
dx1 = in4(1,:);
dy1 = in4(2,:);
theta1 = in3(5,:);
t2 = L_frame.*M_hip;
t3 = M_frame+M_hip;
t5 = (L_frame.*M_frame)./2.0;
t4 = 1.0./t3;
t6 = t2+t5;
dx_frame_CoM_vec = [dx1+dtheta1.*t4.*t6.*cos(theta1);dy1+dtheta1.*t4.*t6.*sin(theta1)];
end
