function dx_fem_CoM_vec = calc_dx_fem_CoM_vec(in1,in2,in3)
%calc_dx_fem_CoM_vec
%    dx_fem_CoM_vec = calc_dx_fem_CoM_vec(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Jul-2024 23:01:49

L_fem = in1(1,:);
L_frame = in1(6,:);
dtheta1 = in3(5,:);
dtheta2 = in3(6,:);
dx1 = in3(1,:);
dy1 = in3(2,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
t2 = theta1+theta2;
t3 = cos(t2);
t4 = sin(t2);
dx_fem_CoM_vec = [dx1+dtheta1.*((L_fem.*t3)./2.0+L_frame.*cos(theta1))+(L_fem.*dtheta2.*t3)./2.0;dy1+dtheta1.*((L_fem.*t4)./2.0+L_frame.*sin(theta1))+(L_fem.*dtheta2.*t4)./2.0];
