%第４起始点の座標　calc_EOM_workから書き出されたファイル

function Coordinate_4th_troch = calc_coordinate_4th_troch(in1,in2)
%CALC_COORDINATE_4TH_TROCH
%    Coordinate_4th_troch = CALC_COORDINATE_4TH_TROCH(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:14

L_4th_troch = in1(4,:);
L_frame = in1(6,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
x1 = in2(1,:);
y1 = in2(2,:);
t2 = theta1+theta2;
Coordinate_4th_troch = [x1+L_4th_troch.*sin(t2)+L_frame.*sin(theta1);y1-L_4th_troch.*cos(t2)-L_frame.*cos(theta1)];
