%M3からプーリーへの接点の座標　calc_EOM_workから書き出されたファイル

function coodinate_M3_to_pulley = calc_coordinate_M3_to_pulley(in1,in2)
%calc_coordinate_M3_to_pulley
%    coodinate_M3_to_pulley = calc_coordinate_M3_to_pulley(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:14

L_fem = in1(1,:);
L_frame = in1(6,:);
L_tib = in1(2,:);
r = in1(7,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
theta3 = in2(7,:);
x1 = in2(1,:);
x3 = in2(3,:);
y1 = in2(2,:);
y3 = in2(4,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = theta1+theta2;
t5 = r.^2;
t6 = x1.*2.0;
t7 = x3.^2;
t8 = y1.*2.0;
t9 = y3.^2;
t15 = -y1;
t10 = L_frame.*t2;
t11 = L_frame.*t3;
t12 = cos(t4);
t13 = sin(t4);
t14 = t4+theta3;
t16 = -t8;
t21 = -t5;
t17 = cos(t14);
t18 = sin(t14);
t19 = t10.*2.0;
t20 = t11.*2.0;
t22 = L_fem.*t12;
t23 = L_fem.*t13;
t24 = t22.*2.0;
t25 = t23.*2.0;
t26 = L_tib.*t17;
t27 = L_tib.*t18;
t28 = t26.*2.0;
t29 = t27.*2.0;
t30 = t11+t23+t27+x1;
t32 = t10+t15+t22+t26;
t31 = t30.^2;
t33 = t6+t20+t25+t29;
t34 = t32.^2;
t35 = t16+t19+t24+t28;
t36 = t33.*x3;
t37 = t35.*y3;
t38 = -t36;
t39 = t7+t9+t31+t34+t37+t38;
t40 = 1.0./t39;
t41 = t21+t39;
t42 = sqrt(t41);
coodinate_M3_to_pulley = [t40.*(t7.*t30+t9.*t30+t21.*t30+t30.*t34+t5.*x3-t31.*x3.*2.0+t30.^3-r.*t32.*t42-r.*t42.*y3+t32.*t33.*y3);-t40.*(t7.*t32+t9.*t32+t21.*t32+t31.*t32+t32.*t38+t21.*y3+t34.*y3.*2.0+t32.^3+r.*t30.*t42-r.*t42.*x3)];
