function angular_moment_list = calc_angular_moment_list(in1,in2,in3,in4)
%CALC_ANGULAR_MOMENT_LIST
%    ANGULAR_MOMENT_LIST = CALC_ANGULAR_MOMENT_LIST(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    30-Jul-2024 14:29:40

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M_fem = in1(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
M_met_beam = in1(9,:);
M_met_pulley = in1(8,:);
M_tib = in1(7,:);
dtheta1 = in4(5,:);
dtheta2 = in4(6,:);
dtheta3 = in4(7,:);
dtheta4 = in4(8,:);
r = in2(7,:);
t2 = L_met.^2;
t3 = L_frame.*M_hip;
t4 = M_frame+M_hip;
t5 = M_met_beam+M_met_pulley;
t7 = (L_frame.*M_frame)./2.0;
t6 = 1.0./t4;
t8 = t3+t7;
t9 = t6.*t8;
t10 = -t9;
angular_moment_list = [dtheta1.*(M_hip.*(L_frame+t10).^2+(L_frame.^2.*M_frame)./1.2e+1+M_frame.*(L_frame./2.0+t10).^2);(L_fem.^2.*M_fem.*(dtheta1+dtheta2))./1.2e+1;(L_tib.^2.*M_tib.*(dtheta1+dtheta2+dtheta3))./1.2e+1;((M_met_beam.*t2)./1.2e+1+(M_met_pulley.*r.^2)./2.0+M_met_beam.*(L_met./2.0-(L_met.*M_met_beam)./(t5.*2.0)).^2+(M_met_beam.^2.*M_met_pulley.*t2.*1.0./t5.^2)./4.0).*(dtheta1+dtheta2+dtheta3+dtheta4)];
