%GE_originの座標　calc_EOM_workから書き出されたファイル

function Coordinate_GE_origin = calc_coordinate_GE_origin(in1,in2)
%calc_coordinate_GE_origin
%    Coordinate_GE_origin = calc_coordinate_GE_origin(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:14

L_GE_origin = in1(5,:);
L_frame = in1(6,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
x1 = in2(1,:);
y1 = in2(2,:);
t2 = theta1+theta2;
Coordinate_GE_origin = [x1+L_GE_origin.*sin(t2)+L_frame.*sin(theta1);y1-L_GE_origin.*cos(t2)-L_frame.*cos(theta1)];
