%重心の座標を計算

function [COM_x,COM_y] = calc_coordinate_COM(q,l_link_list,m_list)
%calc_COM
%    COM = calc_COM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/31 01:50:34
    COM_x=zeros(size(q,1),12);
    COM_y=zeros(size(q,1),12);
    L_fem=l_link_list(1);
    L_tib=l_link_list(2);
    L_met=l_link_list(3);
    L_4th_troch=l_link_list(4);
    L_GE_origin=l_link_list(5);
    L_frame=l_link_list(6);
    %frameの重心座標の計算
    L_frame_CoM = (l_link_list(6)*m_list(5)/2 + l_link_list(6)*m_list(4))/(m_list(5) + m_list(4));
    %metatarsalの端部から重心までの長さ
    L_met_CoM = (l_link_list(3)*m_list(9)/2)/(m_list(8) + m_list(9));
    for i = 1:size(q,1)
        %フレーム重心の座標，速度
        COM_x(i,1) = q(i,1) + L_frame_CoM*sin(q(i,5));
        COM_y(i,1) = q(i,2) - L_frame_CoM*cos(q(i,5));
        %股関節重心の座標，速度
        x_hip = q(i,1) + L_frame*sin(q(i,5));
        y_hip = q(i,2) - L_frame*cos(q(i,5));
        %大腿骨重心の座標，速度
        COM_x(i,2) = x_hip + L_fem/2*sin(q(i,5)+q(i,6));
        COM_y(i,2) = y_hip - L_fem/2*cos(q(i,5)+q(i,6));
        %膝重心の座標，速度
        x_knee = x_hip + L_fem*sin(q(i,5)+q(i,6));
        y_knee = y_hip - L_fem*cos(q(i,5)+q(i,6));
        %脛骨重心の座標，速度
        COM_x(i,3) = x_knee + L_tib/2*sin(q(i,5)+q(i,6)+q(i,7));
        COM_y(i,3) = y_knee - L_tib/2*cos(q(i,5)+q(i,6)+q(i,7));
        %くるぶし重心の座標，速度
        x_ankle = x_knee + L_tib*sin(q(i,5)+q(i,6)+q(i,7));
        y_ankle = y_knee - L_tib*cos(q(i,5)+q(i,6)+q(i,7));
        %足先重心の座標，速度
        COM_x(i,4)  = x_ankle + L_met_CoM*sin(q(i,5)+q(i,6)+q(i,7)+q(i,8));
        COM_y(i,4)  = y_ankle - L_met_CoM*cos(q(i,5)+q(i,6)+q(i,7)+q(i,8));
    
    
    
    
    
    end
