%慣性モーメント　calc_EOM_workから書き出されたファイル

function J_list = calc_J_list(in1,in2)
%calc_J_list
%    J_list = calc_J_list(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Jul-2024 23:01:49

L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
M_fem = in1(6,:);
M_frame = in1(5,:);
M_hip = in1(4,:);
M_met_beam = in1(9,:);
M_met_pulley = in1(8,:);
M_tib = in1(7,:);
r = in2(7,:);
t2 = L_met.^2;
t3 = L_frame.*M_hip;
t4 = M_frame+M_hip;
t5 = M_met_beam+M_met_pulley;
t7 = (L_frame.*M_frame)./2.0;
t6 = 1.0./t4;
t8 = t3+t7;
t9 = t6.*t8;
t10 = -t9;
J_list = [M_hip.*(L_frame+t10).^2+(L_frame.^2.*M_frame)./1.2e+1+M_frame.*(L_frame./2.0+t10).^2;(L_fem.^2.*M_fem)./1.2e+1;(L_tib.^2.*M_tib)./1.2e+1;(M_met_beam.*t2)./1.2e+1+(M_met_pulley.*r.^2)./2.0+M_met_beam.*(L_met./2.0-(L_met.*M_met_beam)./(t5.*2.0)).^2+(M_met_beam.^2.*M_met_pulley.*t2.*1.0./t5.^2)./4.0];
