%外力項　calc_EOM_workから書き出されたファイル
function Q = External_force_matrix(in1,in2,in3,in4,error_CFL,int_error_CFL,derror_CFL)
%External_force_matrix
%    Q = External_force_matrix(IN1,IN2,IN3,IN4,error_CFL,int_error_CFL,derror_CFL)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    11-Jul-2024 19:13:14

Dgain = in4(3,:);
F_hip_x = in1(1,:);
F_hip_y = in1(2,:);
F_heel_x = in1(3,:);
F_heel_y = in1(4,:);
F_toe_x = in1(5,:);
F_toe_y = in1(6,:);
Igain = in4(2,:);
L_fem = in2(1,:);
L_frame = in2(6,:);
L_met = in2(3,:);
L_tib = in2(2,:);
Pgain = in4(1,:);
theta1 = in3(5,:);
theta2 = in3(6,:);
theta3 = in3(7,:);
theta4 = in3(8,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = theta1+theta2;
t5 = L_frame.*t2;
t6 = L_frame.*t3;
t7 = cos(t4);
t8 = sin(t4);
t9 = t4+theta3;
t10 = cos(t9);
t11 = sin(t9);
t12 = t9+theta4;
t13 = L_fem.*t7;
t14 = L_fem.*t8;
t15 = cos(t12);
t16 = sin(t12);
t17 = L_tib.*t10;
t18 = L_tib.*t11;
t19 = L_met.*t15;
t20 = L_met.*t16;
Q = [F_hip_x+F_heel_x+F_toe_x;F_hip_y+F_heel_y+F_toe_y;0.0;0.0;F_hip_x.*t5+F_hip_y.*t6+F_heel_x.*(t5+t13+t17)+F_heel_y.*(t6+t14+t18)+F_toe_x.*(t5+t13+t17+t19)+F_toe_y.*(t6+t14+t18+t20);F_toe_x.*(t13+t17+t19)+F_toe_y.*(t14+t18+t20)+F_heel_x.*(t13+t17)+F_heel_y.*(t14+t18);F_heel_x.*t17+F_heel_y.*t18+F_toe_x.*(t17+t19)+F_toe_y.*(t18+t20);F_toe_x.*t19+F_toe_y.*t20;0.0;Dgain.*derror_CFL+Igain.*int_error_CFL+Pgain.*error_CFL];
