function F = calc_F_pend(Igain,Pgain,error,int_error)
%calc_F_pend
%    F = calc_F_pend(Igain,Pgain,ERROR,INT_ERROR)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Jul-2024 12:50:15

F = [0.0;Igain.*int_error+Pgain.*error];
