function D = calc_D_pend(c,dl,dtheta)
%calc_D_pend
%    D = calc_D_pend(C,DL,DTHETA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Jul-2024 12:50:16

D = [c.*dtheta;c.*dl];
