function C = calc_C_pend(dl,dtheta,l,m,theta)
%calc_C_pend
%    C = calc_C_pend(DL,DTHETA,L,M,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Jul-2024 12:50:15

t2 = cos(theta);
t3 = sin(theta);
C = [(dl.*m.*(t2.*(dl.*t3+dtheta.*l.*t2).*2.0-t3.*(dl.*t2-dtheta.*l.*t3).*2.0+dtheta.*l.*t2.^2.*2.0+dtheta.*l.*t3.^2.*2.0))./2.0;0.0];
