function G = calc_G_pend(dl,dtheta,g,k,l,l_sp,m,theta,x_sp,y_sp)
%calc_G_pend
%    G = calc_G_pend(DL,DTHETA,g,K,L,L_SP,M,THETA,X_SP,Y_SP)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Jul-2024 12:50:15

t2 = cos(theta);
t3 = sin(theta);
t4 = l.*t2;
t5 = l.*t3;
t6 = t4+y_sp;
t7 = -t5;
t10 = (t5-x_sp).^2;
t8 = t7+x_sp;
t9 = t6.^2;
t11 = t9+t10;
t12 = sqrt(t11);
t13 = 1.0./t12;
t14 = -t12;
t15 = l_sp+t14;
G = [g.*m.*t7-(k.*t13.*t15.*(t5.*t6.*2.0-t4.*(t5-x_sp).*2.0))./2.0;(m.*(dtheta.*t2.*(dl.*t3+dtheta.*t4).*2.0-dtheta.*t3.*(dl.*t2+dtheta.*t7).*2.0))./2.0+g.*m.*t2+(k.*t13.*t15.*(t2.*t6.*2.0+t3.*(t5-x_sp).*2.0))./2.0];
