function M = calc_M_pend(l,m,theta)
%calc_M_pend
%    M = calc_M_pend(L,m,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    09-Jul-2024 12:50:15

t2 = cos(theta);
t3 = sin(theta);
t4 = l.^2;
t5 = t2.^2;
t6 = t3.^2;
M = reshape([(m.*(t4.*t5.*2.0+t4.*t6.*2.0))./2.0,0.0,0.0,(m.*(t5.*2.0+t6.*2.0))./2.0],[2,2]);
